services:
  # БД PostgreSQL
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace_inventory
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservices
  #Редис для кэша
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - microservices
    volumes:
      - redisdata:/data
  #Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices
  # Eureka
  eureka-server:
    build:
      context: .
      dockerfile: marketplace-eureka-service/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices

  # Микросервисы
  inventory-service:
    build:
      context: .
      dockerfile: marketplace-inventory-service/Dockerfile
    container_name: inventory-service
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      GRADLE_OPTS: "-Dcheckstyle.skip=true -Dpmd.skip=true"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_started
      order-service:
        condition: service_started
    networks:
      - microservices

  notification-service:
    build:
      context: .
      dockerfile: marketplace-notification-service/Dockerfile
    container_name: notification-service
    restart: unless-stopped
    expose:
      - "8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      GRADLE_OPTS: "-Dcheckstyle.skip=true -Dpmd.skip=true"
    depends_on:
      kafka:
        condition: service_started
    networks:
      - microservices

  order-service:
    build:
      context: .
      dockerfile: marketplace-order-service/Dockerfile
    container_name: order-service
    restart: unless-stopped
    expose:
      - "8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/marketplace_inventory
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      GRADLE_OPTS: "-Dcheckstyle.skip=true -Dpmd.skip=true"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - microservices

  payment-service:
    build:
      context: .
      dockerfile: marketplace-payment-service/Dockerfile
    container_name: payment-service
    restart: unless-stopped
    expose:
      - "8086"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      GRADLE_OPTS: "-Dcheckstyle.skip=true -Dpmd.skip=true"
    depends_on:
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - microservices

  pricing-service:
    build:
      context: .
      dockerfile: marketplace-pricing-service/Dockerfile
    container_name: pricing-service
    restart: unless-stopped
    expose:
      - "8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/marketplace_inventory
      GRADLE_OPTS: "-Dcheckstyle.skip=true -Dpmd.skip=true"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - microservices

  user-service:
    build:
      context: .
      dockerfile: marketplace-user-service/Dockerfile
    container_name: user-service
    restart: unless-stopped
    expose:
      - "8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/marketplace_inventory
      GRADLE_OPTS: "-Dcheckstyle.skip=true -Dpmd.skip=true"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - microservices

  gateway-service:
    build:
      context: .
      dockerfile: marketplace-gateway-service/Dockerfile
    container_name: gateway-service
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      GRADLE_OPTS: "-Dcheckstyle.skip=true -Dpmd.skip=true"
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - microservices



volumes:
  pgdata:
  kafka-data:
  zookeeper-data:
  redisdata:

networks:
  microservices:
    driver: bridge