server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      value-deserializer: org.yrti.notification.kafka.config.KafkaTopicDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "org.yrti.order.events,org.yrti.notification.events"
        spring.json.type.headers: false
        session.timeout.ms: 25000
        heartbeat.interval.ms: 8000
        max.poll.interval.ms: 300000
        request.timeout.ms: 35000
        retry.backoff.ms: 1000

  mail:
    host: smtp.gmail.com
    port: 587
    username: yrtitestproject@gmail.com
    password: pnxnuruizcxzeejf
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true