server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      value-deserializer: org.yrti.notification.kafka.config.KafkaTopicDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "org.yrti.order.events,org.yrti.notification.events"
        spring.json.type.headers: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: yrtitestproject@gmail.com
    password: pnxnuruizcxzeejf
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true