server:
  port: 8085

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Основные маршруты API
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
        - id: pricing-service
          uri: lb://PRICING-SERVICE
          predicates:
            - Path=/api/pricing/**

        # Маршрут для API Docs
        - id: inventory-service-api-docs
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/v3/api-docs
          filters:
            - RewritePath=/inventory/v3/api-docs, /v3/api-docs
        - id: order-service-api-docs
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/v3/api-docs
          filters:
            - RewritePath=/order/v3/api-docs, /v3/api-docs
        - id: user-service-api-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/v3/api-docs
          filters:
            - RewritePath=/user/v3/api-docs, /v3/api-docs
        - id: payment-service-api-docs
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/v3/api-docs
          filters:
            - RewritePath=/payment/v3/api-docs, /v3/api-docs
        - id: pricing-service-api-docs
          uri: lb://PRICING-SERVICE
          predicates:
            - Path=/pricing/v3/api-docs
          filters:
            - RewritePath=/pricing/v3/api-docs, /v3/api-docs
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Inventory Service
        url: /inventory/v3/api-docs
      - name: Order Service
        url: /order/v3/api-docs
      - name: User Service
        url: /user/v3/api-docs
      - name: Payment Service
        url: /payment/v3/api-docs
      - name: Pricing Service
        url: /pricing/v3/api-docs
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true